
# Тестовые данные
GET http://localhost:3123/api HTTP/1.1
###

# Фильмы
## Получить список фильмов
GET http://localhost:5090/films HTTP/1.1
Content-Type: application/json
###

## Создать карточку фильма

POST  http://localhost:5090/films HTTP/1.1
Content-Type: application/json

{
 "title": "Билли Саммер    jhklhс",
 "description":"Новый детективный роман от короля ужасов.",
 "postDate":  "2022-05-12T11:56:37.573Z",
 "genre": "Comedy",
 "released": 1999,
 "previewVideoLink": "www.ya.ru",
 "videoLink": "www.ya.ru",
 "staring":  ["Goga" , "Magoga"],
 "director": "Никита Михалков",
 "runTime": 123,
 "posterImage": "billy-summers.jpg",
 "backgroundImage": "billy-summers.jpg",
 "backgroundColor": "#fcba03",
 "userId": "63da42375e93538a0ac08c15"
}
###

## Получение карточки по идентификатору

GET http://localhost:5090/films/63da42375e93538a0ac08c1c HTTP/1.1

###

## Удаление карточки по идентификатору

DELETE http://localhost:5090/films/63da42375e93538a0ac08c17 HTTP/1.1

###

## Обновление фильма

PATCH http://localhost:5090/films/63d4053fd02d5a662d568c2f HTTP/1.1
Content-Type: application/json

 {
   "title": "Ночной дозор 5",
   "released": "2057"
 }

###

## Получение фильмов по жанру

GET http://localhost:5090/films/genre/thriller?limit=5 HTTP/1.1

###


## Создать комментарий
POST http://localhost:5090/comments HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvYWRzQG92ZXhjby5uZXQiLCJpZCI6IjYzZGQyMjNkZTQ1MTNhODRiMWYzZDZiMCIsImlhdCI6MTY3NTg0NTk3NiwiZXhwIjoxNjc2MDE4Nzc2fQ.Q2PUh2W5sPbHP0dgGONv68IvG3AkEl_5UH9pZ-zzblc

{
  "text": "Как обстоят дела с коробками? Фирменная упаковка сохранена?",
  "rating": 17,
  "movieCardId": "63da42375e93538a0ac08c1c"
}

###

## Список комментариев к фильму

GET http://localhost:5090/films/63da42375e93538a0ac08c17/comments HTTP/1.1


###

# Пользователи
## Регистрация пользователя

POST http://localhost:5090/users/register HTTP/1.1
Content-Type: application/json

 {
   "email": "toads@ovexco.net",
   "avatarPath": "torre.png",
   "name": "Jack",
   "password": "shining"
 }

###

## Авторизация пользователя

POST http://localhost:5090/users/login HTTP/1.1
Content-Type: application/json

 {
   "email": "toads@ovexco.net",
   "password": "shining"
 }

###

## Отправка аватарки пользователю

POST http://localhost:5090/users/63da42375e93538a0ac08c15/avatar HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="avatar.jpg"
Content-Type: image/png

< /Users/ivanmerkulov/tmp/avatar.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###


## Проверка токена пользователя
GET http://localhost:5090/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvYWRzQG92ZXhjby5uZXQiLCJpZCI6IjYzZGQyMjNkZTQ1MTNhODRiMWYzZDZiMCIsImlhdCI6MTY3NTg0NTk3NiwiZXhwIjoxNjc2MDE4Nzc2fQ.Q2PUh2W5sPbHP0dgGONv68IvG3AkEl_5UH9pZ-zzblc

###
