
# Тестовые данные
GET http://localhost:3123/api HTTP/1.1
###

# Фильмы
## Получить список фильмов
GET http://localhost:5090/films HTTP/1.1
Content-Type: application/json
###

## Создать карточку фильма

POST  http://localhost:5090/films HTTP/1.1
Content-Type: application/json

{
 "title": "Билли Саммерс",
 "description":"Новый детективный роман от короля ужасов.",
 "postDate":  "2022-05-12T11:56:37.573Z",
 "genres": "comedy",
 "released": "1999",
 "previewVideoLink": "www.ya.ru",
 "videoLink": "www.ya.ru",
 "staring":  ["Goga" , "Magoga"],
 "director": "Никита Михалков",
 "runTime": "123",
 "posterImage": "billy-summers.png",
 "backgroundImage": "billy-summers.png",
 "backgroundColor": "billy-summers.png",
 "userId": "63da42375e93538a0ac08c15"
}
###

## Получение карточки по идентификатору

GET http://localhost:5090/films/63d4053fd02d5a662d568c2f HTTP/1.1

###

## Удаление карточки по идентификатору

DELETE http://localhost:5090/films/63d4053fd02d5a662d568c2a HTTP/1.1

###

## Обновление объявления

PATCH http://localhost:5090/films/63d4053fd02d5a662d568c2f HTTP/1.1
Content-Type: application/json

 {
   "title": "Ночной дозор 5",
   "released": "2057"
 }

###

## Получение фильмов по жанру

GET http://localhost:5090/films/genre/thriller?limit=5 HTTP/1.1

###
## Список комментариев к фильму

GET http://localhost:5090/films/628a27d729c45f2bf9f6806a/comments HTTP/1.1


###
 # Пользователи
 ## Регистрация пользователя

POST http://localhost:5090/users/register HTTP/1.1
Content-Type: application/json

 {
   "email": "torans@overlook.net",
   "avatarPath": "torrance.png",
   "name": "Jack",
   "password": "shining"
 }

###

